[template]
src = "haproxy.cfg.template"
dest = "/etc/haproxy/haproxy.cfg"

# The key below must be changed to match how you named your
# service in the StackEngine CAC.  Don't forget to also adjust
# this value in `/etc/confd/templates/haproxy/templates/haproxy.cfg.template
keys = [
"/apps/haproxy-backend-instance-haproxy-backend-80/containers"
]
reload_cmd = "supervisorctl reload haproxy"